repos:
- repo: local
  hooks:
    - id: flake8
      name: flake8
      description: wemake-python-styleguide enforcement
      entry: flake8
      args: ["--config=.flake8"]
      language: python
      types: [python]
    - id: mypy
      name: mypy
      entry: mypy --ignore-missing-imports .
      language: system
      types: [python]
      pass_filenames: false
      always_run: true
      verbose: true
