# Generated by Django 3.2 on 2022-04-01 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_change_fields'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genrefilmwork',
            old_name='film_work_id',
            new_name='film_work',
        ),
        migrations.RenameField(
            model_name='genrefilmwork',
            old_name='genre_id',
            new_name='genre',
        ),
        migrations.RenameField(
            model_name='personfilmwork',
            old_name='film_work_id',
            new_name='film_work',
        ),
        migrations.RenameField(
            model_name='personfilmwork',
            old_name='person_id',
            new_name='person',
        ),
    ]
