filebeat.inputs:
  - type: filestream
    id: ugc-logs-input
    paths:
      - /var/log/nginx/*
      - /var/log/ugc_api/*
    json:
      keys_under_root: true
      add_error_key: true

processors:
  - add_tags:
      tags: [ugc_api]

output.logstash:
  enabled: true
  hosts: ["elk-logstash:5045"]